/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Pizza?.. (https://sketchfab.com/PizzaFK)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-cake-36a900d5c93a4ad4a5f341ec221b3aab
Title: Minecraft - Cake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/minecraft_cake/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_2} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
