/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Livio Arango (https://sketchfab.com/livioag)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bonfire-dark-souls-a090bdd8ca6841d1855f3d998697706b
Title: Bonfire / Dark Souls
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bonfire__dark_souls/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Mat_Ash} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Mat_Ash} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Mat_Ash} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Mat_Ash} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Mat_Ash} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Mat_Base} />
        <lineSegments geometry={nodes.Object_8.geometry} material={materials.Mat_Bones} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Mat_Bones} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Mat_Sword-Fire']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
